### ISSUE TITLE
If you type @ and delete it the mentioning dropdown stays

### ISSUE THREAD

**Issue by TheExkaliburg** [TheExkaliburg/MoreFair#42]
https://cdn.discordapp.com/attachments/968972688779513876/968973229970567208/unknown.png

https://discord.com/channels/928501394619658330/968972688779513876/968973230696173568

**Comment by LynnCinnamon** [comment]
This is most likely caused by a box being there when not expected to be. Fixable by just removing all of those boxes instead of only the expected one.
