### ISSUE TITLE
Graping someone breaks the UI

### ISSUE THREAD

**Issue by boozledorf** [TheExkaliburg/MoreFair#45]
![image](https://user-images.githubusercontent.com/7085132/165634638-8d150701-8d1a-4e1c-a89f-a7e600e1836c.png)
Note the rank numbers, and the time to promotion (infinity)

**Comment by LynnCinnamon** [comment]
I believe the error might be in ladder.js@39 wich excludes non-growing rankers from the sorting algorithm used in the frontend. I only patched the visuals in #56 with a sort at the end and further work is required.

**Comment by TheExkaliburg** [comment]
yep i totally agree i think your stuff fixed everything, but im gonna open another issue for myself to clean up my shit in that function ^^'
