### ISSUE TITLE
Accessibility/Suggestion: Light mode option

### ISSUE THREAD

**Issue by derogative** [TheExkaliburg/MoreFair#48]
This report isn't a bug so much as just highlighting potential accessibility issues and a request for the option to select between light mode and dark mode.

Current dark mode with the orange and blue scheme has been causing me eye strain and headaches; I've been checking over the past few hours to verify that it's the current iteration of FairGame that's causing it, and unfortunately have found that if I look at the website for more than a minute or two I begin to squint and feel pain behind one of my eyes.

It may or may not be worth checking into if any other players are experiencing the issue?

I don't expect the layout or design to change for just me, but would like to request the option to select a light mode or a greyscale mode in the future, as the previous black and white version didn't cause me any issues.

Thank you!

**Comment by TheExkaliburg** [comment]
I really wanna do a theme selector, that people can add onto, just having some trouble how to best do that while having the variables of everything at a central point...

So it might take some time till there is actually a light mode but its on high priority for me

**Comment by TheExkaliburg** [comment]
Its's done with the newest update, please enjoy :)
