### ISSUE TITLE
Overlay scrollbars ontop of content

### ISSUE THREAD

**Issue by The-Danfoss** [TheExkaliburg/MoreFair#54]
Overlay scrollbars in MS Edge render over the ladderpoints. Maybe some margins can be added somewhere to prevent this?
![image](https://user-images.githubusercontent.com/667383/165750861-e3f0bba7-6fb4-44ec-9d26-00c9101674b9.png)

**Comment by TheExkaliburg** [comment]
Weird thing is this doesn't happen in my MS Edge version, can you tell me what version you are using and if you are on mobile
![image](https://user-images.githubusercontent.com/34279353/165783352-63176a32-4b52-4883-8559-a778d5a01981.png)
