### ISSUE TITLE
Chat messages are cut off after a certain point with no warning.

### ISSUE THREAD

**Issue by boozledorf** [TheExkaliburg/MoreFair#57]
Messages in chat can be (from what I can tell) arbitrarily large, but the actual sent message is not.  See below.
![image](https://user-images.githubusercontent.com/7085132/165845986-235cf910-b8ee-4d6d-8be9-3d05df51a074.png)
![image](https://user-images.githubusercontent.com/7085132/165846017-f7a52a74-6819-4235-a81e-dabd81c8bb6d.png)

**Comment by TheExkaliburg** [comment]
The fact that the chatbox gets too large should be fixed with issue https://github.com/TheExkaliburg/MoreFair/issues/43 but the other one, should be that you can't fill the message size over the given limit of 140 we currently have
