### ISSUE TITLE
Copy-Pasting issue in Chad

### ISSUE THREAD

**Issue by LynnCinnamon** [TheExkaliburg/MoreFair#88]
With the new Chad system, copy pasting text is still broken.
Pasting formatted Text (i.e. copyint out of chad) will insert a node that will be displayed but not be sent.
==> We are not properly escaping this kind of inserts :/

**Comment by TheExkaliburg** [comment]
i think that worked before the removal of the screenshot copy-paste bug (which wouldn't send but show it in chad)
