### ISSUE TITLE
Top Promoter Rewards overwork

### ISSUE THREAD

**Issue by TheExkaliburg** [TheExkaliburg/MoreFair#89]
Something along the lines of (numbers may change)

auto for 2 ladders (1)
auto for 1 ladder (2-3)

decreasing values of grapes (1-10)
decreasing values of vinegar (1-20)

**Comment by ClueIess** [comment]
How would the decreasing values of grapes/vinegar work?
Like bonus amounts for promoting within those ranks?

Also I like the idea of multiple ways of getting auto, can potentially spice up  the AH ladder if multiple people have a chance at Auto

**Comment by TheExkaliburg** [comment]
not decreasing the counts, but decreasingly high amounts of grapes/vinegar

fe. 1. gets 10, 2. 9, 3. gets 8 and so forth
