### ISSUE TITLE
ETA Colours feel off when 1st

### ISSUE THREAD

**Issue by ClueIess** [TheExkaliburg/MoreFair#91]
Was in 1st with an ETA to promo less than everyone's ETA to catch me yet everyone still showed up as RED.
I feel it would make sense that if you're promo time is less than their ETA it would appear green.

pics in discord

**Comment by boozledorf** [comment]
I'm pretty sure that if a ladder hasn't unlocked, it's actually time to rank 1 rather than time to promote.

**Comment by TheExkaliburg** [comment]
maybe its fixed with the better eta now, check it out and tell me if its working, because i'm not sure ^^
